
* Research Interests
** Theory & Methodology
I'm deeply interested in theory and methodology; how explanations can be formed and evaluated when seeking to explain a system as complex as the economy. Especially in macroeconomics, I hope to explore questions relating to the efficacy of DSGE models and what amendments or alternatives might improve our understanding of the macroeconomy. 

Criticism of DSGE models has been palpable, two examples from Nobel-laureates are Stiglitz's /Where Modern Macroeconomics Went Wrong/ [cite:@stiglitz2017] and Akerlof's /What They Were Thinking Then: The Consequences for Macroeconomics during the Past 60 Years/ [cite:@akerlof2019]. On the other side, Christiano's /On DSGE Models/ [cite:@christiano2018] provides context and responds to criticisms from Stiglitz mentoined above. A paper examining the way DSGE models are calibrated and their efficacy assessed is Korinek's /Thoughts on DSGE Macroeconomics: Matching the Moment, But Missing the Point?/ [cite:@korinek2017]. Relatedly–Gali's /The State of New Keynesian Economics: A Partial Assessment/ [cite:@gali2018]. Glandon's /Macroeconomic Research, Present and Past/ [cite:@glandon2023] provides a recent (2023) survey of the macroeconomics landscape in a historical context. Of course, many questions on this front overlap with microeconomics and rational expectations assumptions–in /The Formation of Expectations, Inflation, and the Phillips Curve/ [cite:@coibion2018] Coibion argues that surveyed empirical micro-evidence appears increasingly at odds with the full-information rational expectation assumption. 

Foundational work in the nature of causation and inference in econometrics fascinates me. Recently Markus summarized much of the discussion on this front to date in /Causal effects and counterfactual conditionals: contrasting Rubin, Lewis and Pearl./ [cite:@markus2021]. Enduring, influential critiques in methodology, such as the Lucas critique [cite:@lucasjr1976] are inspiring work for me. A recent paper examining the neutrality of money in light of the Lucas critique is Clerc's /Dispersed information and the non-neutrality of money: fifty years after Lucas/ [cite:@clerc2022]. Heckman tackles the causality question in a policy context in /The Econometric Model for Causal Policy Analysis/ [cite:@heckman2022]. 

$\newpage$
** Econometrics
Time-series econometrics and stochastic processes are my main areas of interest in econometrics; especially applications in macroeconomics.

I also am interested to explore new types of methodologies for statistical inference such as Bayesian methods like Koop's /Bayesian Multivariate Time Series Methods for Empirical Macroeconomics/ [cite:@koop2009], or that of Ho [cite:@ho2023]. Cascaldi-Garcia in /What is Certain about Uncertainty?/ [cite:@cascaldi-garcia2023] contrasts the various existing measures of uncertainty, risk, and volatility, noting their conceptual distinctions. Ludvigson's /Uncertainty and Business Cycles: Exogenous Impulse or Endogenous Response/ also addresses this delicate question about uncertainty in models of business cycles.

I'm keen to study time-varying parameter models, such as in Leiva-Le\'on's /Endogenous Time Variation in Vector Autoregressions/ [cite:@leiva-leon2023]. Kim covers the issue of endogeneity in models with dynamic parameters in /Dealing with Endogeneity in Regression Models with Dynamic Coefficients/ [cite:@kim2009]. This extends to models of time-varying stochastic parameters, too, like Cross's /Large stochastic volatility in mean VARs/ [cite:@cross2023], or in Bolko [cite:@bolko2023], Arias [cite:@arias2023], or Chan [cite:@chan2023].

I'd like to examine models outside of standard parameterized linear models, such as regime switching models [cite:@kole2023] [cite:@hauzenberger2021], econometric tests for structural change [cite:@fu2023]; approaches modeling nonlinear relationships [cite:@cui2023] [cite:@reif2021],  or that model nonstationary processes [cite:@casini2023] [cite:@blasques2023]. More broadly, I'd like to explore nonparametric techniques in macroeconometrics [cite:@racine2007].

Machine learning techniques increasingly show promise in econometrics, either for forecasting in econometrics [cite:@gouletcoulombe2022] [cite:@wang2023], solving dynamic economic models [cite:@maliar2021], or modeling economic phenomena outright such as market equilibration [cite:@he2023].

$\newpage$
** Macroeconomics
My interests in macro mostly focus on integrated approaches to understanding the real, financial, and monetary systems and their relationship with one another. Especially in the context of business cycle research and in light of modern monetary and fiscal policy interventions and mechanisms. Studying credit expansion/contraction processes and dynamics in the banking sector interest me, too.

Some research in this direction includes:
Mian's /Finance and Business Cycles: The Credit-Driven Household Demand Channel/ [cite:@mian2018].
Cerra's /Hysteresis and Business Cycles/ [cite:@cerra2023].
Sun's /Yield curve and the macroeconomy: Evidence from a DSGE model with housing/ [cite:@sun2023],
Chousakos' /Information Dynamics and Macro Fluctuations/ [cite:@chousakos2023], 
Meggiorini's /Behavioral New Keynesian Models/ [cite:@meggiorini2023], 
D'Agostino's /Expectation-Driven Cycles and the Changing Dynamics of Unemployment/ [cite:@dagostino2022], 
Diamond's /Credit cycles with market-based household leverage/ [cite:@diamond2022].
Greenwood's /Predictable Financial Crises/ [cite:@greenwood2022].
Luk's /Dynamics of secured and unsecured debt over the business cycle/ [cite:@luk2022].
Trotta Vianna's /Business cycle theories after Keynes: A brief review considering the notions of equilibrium and instability/ [cite:@trottavianna2023].

  \newpage{}
** Monetary Economics
My interests here are closely related to broader macro, yet look 'under the hood' a bit more than traditional macro, for example studying banking sector structure, household credit dynamics, and specific financial asset class price dynamics. I particularly want to study dynamic models that incorporate novel policy channels like quantitative easing asset purchase programs that modern central banks employ. Also, examining models with heterogeneity in the agent's balance sheet composition hopefully can shed light on pressing issues like inequality of wealth and income distribution, credit rationing, and other nuanced factors that may affect growth and business cycles.

More generally, example papers of interest include:
Bianco's /Monetary policy and credit flows/ [cite:@bianco2021].
Heise's /The Missing Inflation Puzzle: The Role of the Wage-Price Pass-Through/ [cite:@heise2022].
Palma's /The real effects of monetary expansions: Evidence from a large-scale historical experiment./ [cite:@palma2022].
Guerron-Quintana's /On Liquidity Shocks and Asset Prices/ [cite:@guerron-quintana2022].
Akinci's /Credit Spreads, Financial Crises, and Macroprudential Policy/ [cite:@akinci2022].
Bhattarai's /Time consistency and duration of government debt: A model of quantitative easing/ [cite:@bhattarai2023].
Ter Ellen's /Narrative Monetary Policy Surprises and the Media/ [cite:@terellen2022].
Sims' /The Four-Equation New Keynesian Model/ [cite:@sims2023].
Bianchi's /Monetary Policy and Asset Valuation/ [cite:@bianchi2022].
Caballero's /Global imbalances and policy wars at the zero lower bound/ [cite:@caballero2021].
Blanchet's /Wealth inequality dynamics in europe and the united states: Understanding the determinants/ [cite:@blanchet2023].
Lee's /Wealth Inequality and Endogenous Growth/ [cite:@lee2023]. 
Reis'  /Helicopter Money: What Is It and What Does It Do?/ [cite:@reis2022].
Matsumoto's /Foreign reserve accumulation, foreign direct investment, and economic growth/ [cite:@matsumoto2022].
Feinstein's /Interbank asset-liability networks with fire sale management/ [cite:@feinstein2023]. 
Anzuini's /The non-linear effects of the Fed asset purchases/ [cite:@anzuini2022]. 

  \newpage{}
** Financial Economics
When I worked in asset management, I realized how much money was invested by institutions according to mandates and strucured, rules-based approaches. This leads to the possibility of emergent synchronization and comovement in some of the largest pools of capital in the world if the strategies for rules-based investing resemble one another. An example of research in this direction is Buffa [cite:@buffa2023]. Lochstoer [cite:@lochstoer2022] examines the imperfect and time-delayed reactions of many market participants, providing insight on stylized facts otherwise difficult to reconcile like a weak or even negative risk‐return trade‐offs.

Swanson [cite:@swanson2021] measured the effects of federal reserve forward guidance and asset purchases on financial markets. Pflueger [cite:@pflueger2022] also explores the increasingly important impact the Fed and other central banks can have on financial markets and the behavior of agents and economic sectors. A different perspective on developments leading to the GFC is given by Alban [cite:@albanesi2022], wherein the rise in mortgage defaults were concentrated among prime borrowers, and that life cycle effects and mortgage investor activity are primary factors behind the evolution of debt and default in this period.

The dyanmics of sovereign debt accumulation, and current and historical crises, especially on the household and firm sector interests me. Mitchener [cite:@mitchener2023] provides timely analysis of the incresing sovereign debt levels, potential rollover problems, concerns about sustainability, and historical mechanisms for propogation of sovereign debt risks to households and firms. Feldhutter [cite:@feldhutter2023] highlights the importance of treating debt stochsatically and the improvement of credit spread models by doing so. Debt sustainability, especially in a low interest rate world is examined by Mehrotra [cite:@mehrotra2021].

  \newpage{}
** Growth Theory, Technology, Capital Theory
I've always been puzzled by the treatment of 'capital' in many economic models. No doubt others have been too (for instance in the Cambridge Capital Controversies [cite:@burmeister2000]). Especially in today's technological and software-laden economy, the distinction between intangible and tangible capital is more pressing than ever. Many conversations in my portfolio consulting job centered around how to treat intangibles on the balance sheet of firms during valuation of the company. Exploring intangible capital, especially given the rise of capitalized R&D, software focused firms and even artificial intelligenceand, and its relation to economic growth and production theory is of high interest to me. Corrado [cite:@corrado2022] provides a great overview on the problem and relates it to modern discussions and accounting conventions in growth theory. Additionally, intangible vs. tangible capital structures may impact efficacy of some policy transmission channels. For instance Dottling [cite:@dottling2023] found that investment and stock prices of firms with relatively more intangible assets respond less to monetary policy.
Some additional papers include:
- Jovanovic, B., & Ma, S. (2023). Growth through Learning. Review of
  Economic Dynamics, 50(),
  211–234. http://dx.doi.org/10.1016/j.red.2023.07.002

- Stokey, N. L. (2021). Technology and skill: Twin engines of
  growth. Review of Economic Dynamics, 40(),
  12–43. http://dx.doi.org/10.1016/j.red.2020.08.001

- Growiec, J. (2023). What will drive global economic growth in the
  digital age? Studies in Nonlinear Dynamics \& Econometrics, 27(3),
  335–354. http://dx.doi.org/10.1515/snde-2021-0079

- Rabinovich, J. (2023). Tangible and intangible investments and sales
  growth of US firms. Structural Change and Economic Dynamics, 66(),
  200–212. http://dx.doi.org/10.1016/j.strueco.2023.05.001

- Arthur, W. B. (2011). The nature of technology: what it is and how
  it evolves. New York London Toronto Sydney: Free Press.

  \newpage{}
** Political Economy, Structural Change
Underlying structures in monetary and political institutions seems deeply related to the macroeconomic dynamics that emerges over time. I hope to study this historically (e.g., monetary regimes in U.S. history like the Gold Standard, Bretton Woods system, Petrodollar system, etc.), econometrically and theoretically.

Cogley in /Structural breaks in an endogenous growth model [Monetary policy regimes and beliefs]/ [cite:@cogley2022] studied the effects of parameter uncertainty prompted by structural breaks, finding that agents in their model respond differently to uncertainty prompted by regime shifts in shock processes than they react to comparable perceived increases in shock volatility. Monopoly power and its effects on the economy in the U.S. are considered by Eggertsson [cite:@eggertsson2021]. Grossman covers /The Elusive Explanation for the Declining Labor Share/ [cite:@grossman2022]. Herrendorf studies /Structural change in investment and consumption: A unified analysis [Capital deepening and non-balanced economic growth]/ [cite:@herrendorf2021].

\newpage{}
** Economic Dynamics & Complex Systems and Networks
Models accounting for the complexity in macroeconomic dynamics interest me. As Barnett points out in /Bifurcation of Macroeconometric Models and Robustness of Dynamical Inferences/ [cite:@barnett2015] "While existence of bifurcation boundaries is well known in economic theory, econometricians using macroeconometric models rarely take bifurcation into consideration, when producing policy simulations from macroeconometrics models. Such models are routinely simulated only at the point estimates of the models' parameters."

There are many heterodox approaches to "complexity" in economics, but I think Hommes' /Behavioral and Experimental Macroeconomics and Policy Analysis: A Complex Systems Approach/ [cite:@hommes2021] provides a nice summary of why this perspective is worth paying attention to in theory and policy. Generally, Hommes' work ([[https://www.uva.nl/en/profile/h/o/c.h.hommes/c.h.hommes.html?cb#Profile][URL]]) provides an examples of complex systems inspired approaches, especially emphasizing the role of expectations, belief formation and feedback mechanisms in real, financial and monetary variables as well as bifurcations and changes in system stability.

Other exciting work in dynamics that inspires me includes
- Hommes, C. H. (2005). Heterogeneous agent models in economics and
  finance.
- Elliott, M., & Golub, B. (2022). Networks and Economic
  Fragility. Annual Review of Economics, 14(1),
  665–696. http://dx.doi.org/10.1146/annurev-economics-051520-021647
- Barnett, W. A., Bella, G., Ghosh, T., Mattana, P., & Venturi,
  B. (2023). Controlling chaos in New Keynesian
  macroeconomics. Studies in Nonlinear Dynamics \& Econometrics,
  27(2), 219–236. http://dx.doi.org/10.1515/snde-2021-0106
- Gaiv\~ao, Jos\'e Pedro, & Peixe, T. (2021). Periodic Attractor in
  the Discrete Time Best-Response Dynamics of the Rock-Paper-Scissors
  Game. Dynamic Games and Applications, 11(3),
  491–511. http://dx.doi.org/10.1007/s13235-020-00371-y
- Barnett, W. A., Jawadi, F., & Ftiti, Z. (2020). Causal relationships
  between inflation and inflation uncertainty. Studies in Nonlinear
  Dynamics \& Econometrics, 24(5), http://dx.doi.org/10.1515/snde-2019-0094
            
  \newpage{}
** Game Theory
Dynamic games, learning and adaptation, evolutionary game theory. Intersection between game theory and machine learning models. 
- Sawa, R., & Wu, J. (2023). Statistical inference in evolutionary
  dynamics. Games and Economic Behavior, 137(),
  294–316. http://dx.doi.org/10.1016/j.geb.2022.11.008

- Saha, I., & Kavitha, V. (2023). Systemic-Risk and Evolutionary
  Stable Strategies in a Financial Network. Dynamic Games and
  Applications, 13(3),
  897–928. http://dx.doi.org/10.1007/s13235-022-00488-2

- Battigalli, P., Panebianco, F., & Pin, P. (2023). Learning and
  selfconfirming equilibria in network games. Journal of Economic
  Theory, 212(), 105700. http://dx.doi.org/10.1016/j.jet.2023.105700

- Phade, S. R., & Anantharam, V. (2021). Learning in Games with
  Cumulative Prospect Theoretic Preferences. Dynamic Games and
  Applications, (), . http://dx.doi.org/10.1007/s13235-021-00398-9

- Sorin, S. (2022). Continuous Time Learning Algorithms in
  Optimization and Game Theory. Dynamic Games and Applications, (),
  . http://dx.doi.org/10.1007/s13235-021-00423-x

- Myerson, R. B. (2023). Game Theory and the First World War. Journal
  of Economic Literature, 61(2),
  716–735. http://dx.doi.org/10.1257/jel.20211571

- Penta, A., & Zuazo-Garin, Peio (2022). Rationalizability,
  observability, and common knowledge [Player importance and forward
  induction]. Review of Economic Studies, 89(2), 948–975.
 
  \newpage{}
** Economics & Philosophy
Ex-post empirical analysis, statistical explanation of observed economic data. Prediction vs. accommodation (of data) distinction in the philosophy of science; many approaches in economics aim to retroactively 'fit' stylized facts in a model, yet there are numerous often entirely contradictory sets of models which all 'fit the data' post-facto. Taleb's books on the 'probability veil' and black swans [cite:@taleb2020] [cite:@taleb2016] [cite:@taleb2007]. Nature of predictability in complex economies. Problem of induction in the philosophy of science [cite:@hume1779].
- Hayek, F. A. (1945). The use of knowledge in society. American
  Economic Review, 35(4), 519–560.

- Moller, D. (2017). Property and the creation of value. Economics and
  Philosophy, 33(1), 1–23.

- H\~A\textcopyrightdoin, Cyril (2017). Institutions, rule-following
  and game theory. Economics and Philosophy, 33(1), 43–72.

- Basu, K. (2018). Markets and Manipulation: Time for a Paradigm
  Shift? Journal of Economic Literature, 56(1),
  185–205. http://dx.doi.org/10.1257/jel.20161410

- Karni, E. (2017). States of nature and the nature of
  states. Economics and Philosophy, 33(1), 73–90.

- Lauwers, L., & Vallentyne, P. (2016). Decision theory without finite
  standard expected value. Economics and Philosophy, 32(3), 383–407.

- Courtois, P., Nessah, R., & Tazda\~A\textasciimacront, Tarik
  (2015). How to play games? Nash versus berge behaviour
  rules. Economics and Philosophy, 31(1), 123–139.

  \newpage{}
